import test_config as config

# team compositions and channels
TEAM_FILE = config.TEAM_FILE
PLAYER_FILE = config.PLAYER_FILE
GENERAL_CHANNEL = config.GENERAL_CHANNEL 

# point calculation
RELATIVE_STANDARD_DEVIATION = config.RELATIVE_STANDARD_DEVIATION
POINTS_PER_KAFFNESS = config.POINTS_PER_KAFFNESS
POINTS_PER_GRADE = config.POINTS_PER_GRADE

# zonic kaffness
POINTS_PER_CONNECTED_ZONE_LESS_THAN_6 = config.POINTS_PER_CONNECTED_ZONE_LESS_THAN_6
POINTS_PER_BAD_CONNECTIVITY_INDEX = config.POINTS_PER_BAD_CONNECTIVITY_INDEX
POINTS_FOR_NO_TRAIN = config.POINTS_FOR_NO_TRAIN
POINTS_FOR_MONGUS = config.POINTS_FOR_MONGUS

# emoji dictionary
EMOJI = config.EMOJI

# number of catchers
NUM_CATCHERS = config.NUM_CATCHERS

# bounty system
BOUNTY_BASE_POINTS = config.BOUNTY_BASE_POINTS
BOUNTY_START_POINTS = config.BOUNTY_START_POINTS
BOUNTY_PERCENTAGE = config.BOUNTY_PERCENTAGE

# times
UNSPECIFIC_TIME = config.UNSPECIFIC_TIME
SPECIFIC_PERIOD = config.SPECIFIC_PERIOD
