import test_config as config

# team compositions and channels
TEAM_FILE = config.TEAM_FILE
PLAYER_FILE = config.PLAYER_FILE
GENERAL_CHANNEL = config.GENERAL_CHANNEL 

# point calculation
RELATIVE_STANDARD_DEVIATION = config.RELATIVE_STANDARD_DEVIATION
POINTS_PER_KAFFNESS = config.POINTS_PER_KAFFNESS
POINTS_PER_GRADE = config.POINTS_PER_GRADE
ZONEABLE_AND_ZONED_BONUS = config.ZONEABLE_AND_ZONED_BONUS
POINTS_PER_WALKING_MINUTE = config.POINTS_PER_WALKING_MINUTE
POINTS_PER_STATIONARY_MINUTE = config.POINTS_PER_STATIONARY_MINUTE
POINTS_PER_TRAVEL_MINUTE = config.POINTS_PER_TRAVEL_MINUTE
START_ZONE = config.START_ZONE

# zonic kaffness
POINTS_PER_CONNECTED_ZONE_LESS_THAN_6 = config.POINTS_PER_CONNECTED_ZONE_LESS_THAN_6
POINTS_PER_BAD_CONNECTIVITY_INDEX = config.POINTS_PER_BAD_CONNECTIVITY_INDEX
POINTS_FOR_NO_TRAIN = config.POINTS_FOR_NO_TRAIN
POINTS_FOR_MONGUS = config.POINTS_FOR_MONGUS

# emoji dictionary
EMOJI = config.EMOJI

# number of catchers
NUM_CATCHERS = config.NUM_CATCHERS

# times
UNSPECIFIC_TIME = config.UNSPECIFIC_TIME
TSUERI_TIME = config.TSUERI_TIME
NORMAL_MODE_TIME = config.NORMAL_MODE_TIME
SPECIFIC_PERIOD = config.SPECIFIC_PERIOD

# shops
GLOBAL_SHOPS = config.GLOBAL_SHOPS
GLOBAL_SHOP_PRIZE = config.GLOBAL_SHOP_PRIZE
FINAL_SHOPS_PRIZE = config.FINAL_SHOPS_PRIZE
